export const TOGGLE_ENABLED_CHANNEL = 'backend.TOGGLE_ENABLED_CHANNEL';
export const ENABLE_CHANNEL = 'backend.ENABLE_CHANNEL';
export const DISABLE_CHANNEL = 'backend.DISABLE_CHANNEL';
export const SET_ENABLED_CHANNELS = 'backend.SET_ENABLED_CHANNELS';
